version: '3.3'

services:

  mongodb:
    image: mongo:4.2-bionic
    container_name: mongodb
    restart: unless-stopped    
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./mongo-data:/var/lib/mongo
