version: '3.8'

services:
  
  cache:
    image: redis:7.0-alpine
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81    
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes: 
      - ./redis-data:/var/lib/redis
